jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - '5.34'
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm --installdeps .
      - run: prove -lv t
